# FILEPATH: d:\full-stack-restaurant\src\docker\docker-compose.yml

# This docker-compose file defines a service named "db" that uses the official Postgres image.
# The service is configured to restart always and exposes port 5432 for external access.
# The environment variables POSTGRES_USER, POSTGRES_PASSWORD, and POSTGRES_DB are set to myuser, mypassword, and mydb respectively.
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
